<?php

namespace Phantestic\TestLoader;

use Evenement\EventEmitterInterface;

class ComposerClassmapObjectTestLoader implements TestLoaderInterface
{
    /**
     * @var string
     */
    protected $path;

    /**
     * @var string
     */
    protected $file;

    /**
     * @var string
     */
    protected $method;

    /**
     * @var \Evenement\EventEmitterInterface
     */
    protected $emitter;

    /**
     * @var string
     */
    protected $class;

    /**
     * @param string $path Path to an autoload_classmap.php file generated by Composer
     * @param \Evenement\EventEmitterInterface $emitter
     * @param string $file Regular expression used to filter test files from the classmap
     * @param string $method Regular expression used to filter test methods from classes
     * @param string $class Fully qualified name of a class that implements TestCaseInterface
     */
    public function __construct(
        $path,
        EventEmitterInterface $emitter = null,
        $file = '/Test\.php$/',
        $method = '/^test/',
        $class = '\\Phantestic\\TestCase\\TestCase'
    )
    {
        if (!is_readable($path)) {
            throw new \RuntimeException(
                '$path does not reference a readable file: ' . $path
            );
        }

        $this->path = $path;
        $this->emitter = $emitter;
        $this->file = $file;
        $this->method = $method;
        $this->class = $class;
    }

    public function getIterator()
    {
        $case = $this->class;
        $classmap = require $this->path;
        $tests = [];
        foreach ($classmap as $class => $file) {
            if (!preg_match($this->file, $file)) {
                continue;
            }
            $reflector = new \ReflectionClass($class);
            $methods = $reflector->getMethods(\ReflectionMethod::IS_PUBLIC & ~\ReflectionMethod::IS_STATIC);
            foreach ($methods as $method) {
                if (!preg_match($this->method, $method)) {
                    continue;
                }
                $instance = new $class;
                $test = new $case([$instance, $method->name]);
                $tests[] = $test;
                if ($this->emitter) {
                    $this->emitter->emit('phantestic.loader.loaded', [$test, $instance, $class, $method->name]);
                }
            }
        }
        return new \ArrayIterator($tests);
    }
}
