<?php

namespace Phantestic\TestLoader;

use Evenement\EventEmitterInterface;

class ClassmapFileObjectTestLoader extends ClassmapObjectTestLoader
{
    /**
     * @var string
     */
    protected $path;

    /**
     * @param string $path Path to an autoload_classmap.php file generated by Composer
     * @param \Evenement\EventEmitterInterface $emitter
     * @param string $file Regular expression used to filter test files from the classmap
     * @param string $method Regular expression used to filter test methods from classes
     * @param string $class Fully qualified name of a class that implements TestCaseInterface
     */
    public function __construct(
        $path,
        EventEmitterInterface $emitter = null,
        $file = '/Test\.php$/',
        $method = '/^test/',
        $class = '\\Phantestic\\TestCase\\TestCase'
    )
    {
        if (!is_readable($path)) {
            throw new \RuntimeException(
                '$path does not reference a readable file: ' . $path
            );
        }
        $this->path = $path;

        parent::__construct($emitter, $file, $method, $class);
    }

    public function getClassmap()
    {
        return require $this->path;
    }
}
